workflows:
  unity-android:
    name: Build Unity Android APK
    max_build_duration: 30
    environment:
      vars:
        UNITY_VERSION: 2022.3.9f1
      unity: $UNITY_VERSION
    scripts:
      - name: Activate Unity License
        script: |
          echo "Skipping activation (use personal license or link manually)"
      - name: Install Dependencies
        script: |
          sudo apt update
          sudo apt install -y zip unzip libgtk-3-dev libgl1-mesa-dev libxcursor-dev
      - name: Build Android
        script: |
          /opt/unity/Editor/Unity \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile \
            -projectPath . \
            -buildTarget Android \
            -executeMethod BuildScript.BuildAndroid \
            -quit
    artifacts:
      - build/**/*.apk
      
